### ISSUE TITLE
Neptune 2D support

### ISSUE THREAD

**Issue by mlee12382** [Toylerrr/ELEGOO_Neptune2_Cura#2]
The profile only allows 1 extruder and is therefore not compatible with the 2D without manually editing the elegoo_neptune_2.def.json to enable a 2nd extruder. line 15 on the .json should read as follows:       "1": "elgoo_neptune2_extruder_0" 
I didn't change the typo on elegoo as I wasn't sure if it was a variable used in another file that might break something if I changed it.

**Comment by Toylerrr** [comment]
Wowza I didn't even notice the elegoo typo on the extruder good catch. Ill work on adding 2D support.

**Comment by MarcelMo** [comment]
I just got the printer, too. By now I figured out there is a "shared heater" setting, which was moved into the "printer settings" plugin, cause there seems to be need for some more tuning. Also I was unable to find any information on the hotend. I analysed the example gcode a bit and there was a 80mm retract before each filament change. I will try to find more.
https://github.com/Ultimaker/Cura/issues/9016
So I guess, the templates need some more fine tuning, before it is working out of the box, right ?

**Comment by mlee12382** [comment]
Yeah, I pointed out the start and stop gcode to Tyler last night, I was trying to figure out how to add it to the default profile before bed but didn't have much luck, you can add it manually if you want, start code is G1 F1200 E80 >enter> G92 E0 and end code is G1 F1600 E-80 >enter> G92 E0 add that for both extruders, I didn't get a chance to test printing with it yet either, the shared heater is an option you can make visible for the right side quality panel too if it's not set already. That should give you a temporary work around in theory until he gets it sorted.

**Comment by Toylerrr** [comment]
![image](https://user-images.githubusercontent.com/4400902/153047097-48c32961-e81b-4c2b-b429-93bc4de9d524.png)
![image](https://user-images.githubusercontent.com/4400902/153047121-220e1a19-b920-4c15-a2bb-0bec39f7e1fa.png)
Just confirming this is what you mean?

**Comment by mlee12382** [comment]
Yup and then they're both "extruder 1"

**Comment by MarcelMo** [comment]
First, the extruder number for the second extruder is wrong at the moment - both extruders are numbered 0.
elegoo_neptune2_extruder_1.def.json:11
  "extruder_nr": { "default_value": 1 },

I activated relative extrusion, to make the code more readable.

Enable "extruders share nozzle" 
"shared nozzle initial retraction" and "nozzle switch retraction distance" to 80.0 

I activated the prime tower, but the problem is that priming is happening on layer change, but should be on color change.
So I activate "nozzle switch extra prime amount" and set it to 10mm³, which is just a guess. I don't know how much ... worst case would be 40m³, which is roughly the 16mm heated zone volume - if it even is 16mm.

A filament change looks a bit like this now:
```
G1 F1200 E-80
G1 F600 Z5.6
T1
M204 S5000
M205 X30 Y30
G1 F1200 E74

```
And now the simulation looks like everything is working. No scripts needed.
I will run the print now. Till later...

**Comment by MarcelMo** [comment]
Everything seems to work. Filament change and priming on color change, just as I hoped. I use black and some green. The green is very dirty, so I guess I will have to increase the prime volume a lot. I will double the value and try again.

Still not enough - I wonder if I even use the right value...

**Comment by MarcelMo** [comment]
![image](https://user-images.githubusercontent.com/9505718/153086376-0de2f23d-5faa-496f-80ea-7656da88724b.png)

This works for me. I tried 40mm³ prime minimum volume, but that wasn't enough.
Still, some stringing and maybe some overextrusion, but the rest is just fine tuning, I guess. (Btw. this is a frog...)

![image](https://user-images.githubusercontent.com/9505718/153086912-a9f10c45-1a5a-4cf3-b7d6-699d0fe050e6.png)
![image](https://user-images.githubusercontent.com/9505718/153086939-65c9c5c9-4c36-4bc6-815a-6bc521b995cf.png)

**Comment by mlee12382** [comment]
[Updated Defs.zip](https://github.com/Toylerrr/ELEGOO_Neptune2_Cura/files/8028797/Updated.Defs.zip)
Check these out I think it should have everything fixed this way I left the neptune 2 def and split 2 more for the 2D and updated them with the start/end code.
 Also Marcel the purge volumes are going to be something that you have to tune for different filaments / colors, that's not something that needs to be in the cura printer definitions that Tyler is providing imo. Depending on the color it's going to take more or less to purge to the new color, white for instance takes a lot more purge volume when switching to it from other colors.

**Comment by mlee12382** [comment]
Also just noticed on the main printer end code on the 2D the retract and raise should be G1 E-80 Z0.2 F1600 instead of G1 E-2 Z0.2 F1600
And the extruder_nr should be set to 1 for elegoo_neptune2D_extruder_1.def.json I missed that also
Found more to add to the elegoo_neptune_2D.def.json to fix the shared heater / nozzle issue Marcel mentioned add the following lines:
        "machine_extruders_share_heater": {"default_value": true},
        "machine_extruders_share_nozzle": {"default_value": true},
        "machine_always_write_active_tool": {"default_value": true},

**Comment by mlee12382** [comment]
[Updated_Defs.zip](https://github.com/Toylerrr/ELEGOO_Neptune2_Cura/files/8101122/Updated_Defs.zip)
Here is the updated files as promised for you to look over. :)

**Comment by Toylerrr** [comment]
Added the updates and fixes should have solved these problems. Please reopen this ticket if there are problems or open a new one.
